### 전처리 데이터 로딩 테스트

### 1. 따릉이 사용 내역 데이터 로딩

In [ ]:
import pandas as pd

usage_all = pd.read_parquet("processed_data/usage_all.parquet")

print(usage_all.shape)
display(usage_all.head())

(158381697, 6)

       자전거번호       date  hour  시간별_총이용시간  시간별_총이용거리  시간별_이용횟수
0  SPB-00385 2021-02-01    11        3.0      560.0         1
1  SPB-00385 2021-02-01    16       14.0     2320.0         1
2  SPB-00385 2021-02-01    17        7.0     2000.0         1
3  SPB-00385 2021-02-01    23        5.0     1230.0         1
4  SPB-00385 2021-02-02     6        7.0     1380.0         1

In [2]:
display(usage_all.tail())

               자전거번호       date  hour  시간별_총이용시간  시간별_총이용거리  시간별_이용횟수
158381692  SPB-85099 2025-12-24     7       13.0    1679.56         1
158381693  SPB-85099 2025-12-31    13        5.0     600.35         1
158381694  SPB-85100 2025-12-17    11       25.0    3784.31         1
158381695  SPB-85100 2025-12-18    13        4.0     724.63         1
158381696  SPB-85100 2025-12-21    14       49.0    1531.16         1

### 2. 고장 내역 데이터 로딩

In [3]:
repair_all_2 = pd.read_parquet("processed_data/repair_all_2.parquet")

print(repair_all_2.shape)
display(repair_all_2.head())

(779052, 4)

       자전거번호       date  hour  고장구분
0  SPB-41936 2021-01-01     0   기타
1  SPB-42181 2021-01-01     2  타이어
2  SPB-36237 2021-01-01     3   기타
3  SPB-33399 2021-01-01     4    체인
4  SPB-36328 2021-01-01     8   기타

In [4]:
display(repair_all_2.tail())

            자전거번호       date  hour 고장구분
779047  SPB-68754 2025-12-31    23   체인
779048  SPB-62680 2025-12-31    23  기타
779049  SPB-34168 2025-12-31    23   체인
779050  SPB-34168 2025-12-31    23  기타
779051  SPB-71935 2025-12-31    23   체인

In [6]:
repair_all_2 = pd.read_csv(
    "processed_data/repair_all_2.csv",
    encoding='cp949'
)

print(repair_all_2.shape)
display(repair_all_2.head())

(779052, 4)

       자전거번호        date  hour  고장구분
0  SPB-41936  2021-01-01     0   기타
1  SPB-42181  2021-01-01     2  타이어
2  SPB-36237  2021-01-01     3   기타
3  SPB-33399  2021-01-01     4    체인
4  SPB-36328  2021-01-01     8   기타

In [7]:
display(repair_all_2.tail())

            자전거번호        date  hour 고장구분
779047  SPB-68754  2025-12-31    23   체인
779048  SPB-62680  2025-12-31    23  기타
779049  SPB-34168  2025-12-31    23   체인
779050  SPB-34168  2025-12-31    23  기타
779051  SPB-71935  2025-12-31    23   체인